export default {
  appEyebrow: 'FERRAMENTA DE STOCK', appTitle: 'Contagem de Literatura', install: 'Instalar', installAria: 'Instalar aplicação', primaryNavigation: 'Navegação principal', unitSuffix: 'g / exemplar', calibrationSummary: '{count} exemplares · {weight}', historySummary: '{weight} · quantidade estimada: {quantity} {copies}', approximate: '≈', navCount: 'Contar', navLiterature: 'Literaturas', navStock: 'Stock', navHistory: 'Histórico',
  countHeading: 'Contar stock', countIntro: 'Escolha uma literatura para começar.', scan: 'Ler código QR', enterCode: 'Introduzir código', browseLiterature: 'Ver literaturas', cameraHelp: 'A leitura QR usa a câmara do dispositivo. Também pode introduzir o código manualmente.',
  code: 'Código', codename: 'Codinome (opcional)', calibration: 'Calibração', calibrationCount: 'Exemplares contados', weight: 'Peso total', grams: 'g', save: 'Guardar', cancel: 'Cancelar', newLiterature: 'Nova literatura', unitWeight: 'Peso por exemplar', recalibrate: 'Recalibrar', editCodename: 'Editar codinome', deleteLiterature: 'Eliminar literatura',
  chooseLocation: 'Escolha a localização', estante: 'Estante', karinhu: 'Karinhu', armazem: 'Armazém', pileWeight: 'Peso da pilha', calculate: 'Calcular', estimatedQuantity: 'Quantidade estimada', copies: 'exemplares', calculation: 'Cálculo', saveCount: 'Guardar contagem',
  literatureHeading: 'Literaturas', search: 'Pesquisar código ou codinome', noLiterature: 'Ainda não há literaturas. Introduza um código para começar.', stockHeading: 'Stock por literatura', total: 'Total', notCounted: 'Não contado', includesCounted: 'O total inclui apenas as localizações já contadas.', historyHeading: 'Histórico', noHistory: 'Ainda não há pesagens guardadas.', deleteRecord: 'Eliminar registo', backup: 'Cópia de segurança', exportData: 'Exportar dados', importData: 'Importar dados', importConfirm: 'A importação substitui os dados atuais. Deseja continuar?',
  qrHeading: 'Ler código QR', qrDenied: 'Não foi possível usar a câmara. Verifique a permissão do navegador ou introduza o código manualmente.', qrUnsupported: 'Este navegador não suporta leitura QR. Introduza o código manualmente.', qrDecoded: 'Conteúdo lido do QR', useCode: 'Usar como código', continueManual: 'Introduzir código manualmente', stopCamera: 'Fechar leitor',
  saved: 'Guardado.', deleted: 'Registo eliminado.', confirmDelete: 'Eliminar esta literatura e os seus registos de pesagem?', imported: 'Cópia importada.', exported: 'Cópia de segurança criada.', invalidBackup: 'Ficheiro de cópia inválido. Os dados atuais foram mantidos.', invalidCode: 'Introduza um código.', invalidCount: 'O número de exemplares deve ser maior que zero.', invalidWeight: 'Introduza um peso válido maior que zero.', invalidStockWeight: 'Introduza um peso válido igual ou maior que zero.', notCalibrated: 'Esta literatura ainda não tem calibração.',
  month: 'Stock do mês', installHelp: 'Para instalar, use o menu do navegador e escolha «Instalar aplicação» ou «Adicionar ao ecrã principal».', dateUnknown: 'Data indisponível', searchNoResults: 'Nenhuma literatura encontrada.', qrValue: 'Conteúdo QR', cameraBusy: 'A câmara está a ser usada por outra aplicação.'
};
